dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install --upgrade setuptools wheel pipenv
  - pipenv install --dev
  - pipenv run python setup.py install
script:
  - pipenv run pytest --cov=./
after_success:
  - pipenv run coveralls