language: python
python:
  - "3.7"
install:
  - pip install --upgrade setuptools wheel pipenv
  - pipenv install --dev
  - python setup.py install
script:
  - pytest --cov
after_success:
  - coveralls